export enum ErrorCodes {
    UNIQUE_CONSTRAINT_VIOLATION = 'UNIQUE_CONSTRAINT_VIOLATION',
    VALIDATION_FAILED_ERROR = 'VALIDATION_FAILED_ERROR',
    QUERY_FAILED_ERROR = 'QUERY_FAILED_ERROR',
    AUTHORIZATION_FAILED_ERROR = 'AUTHORIZATION_FAILED_ERROR',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
}